### ISSUE TITLE
NormalizeError not found

### ISSUE THREAD

**Issue by lucienimmink** [Wojteek/diacritics-normalizr#2]
Hi,

I noticed that the Error class is not exported. this results in a type error in the index.d.ts file on line 2:
```export { NormalizeError } from './error/NormalizeError';```

**Comment by Wojteek** [comment]
Hi @lucienimmink 

Thank you for reporting! I haven't noticed it before.

I've just fixed it and released a new version (1.0.2 6a6c40eb42c83d8c3ae347cad4a1ed0c41b42b91).
